awslabs/aws-crt-dotnet

- aws-crt-http/Http.cs
- aws-crt-http/HttpConnection.cs
- aws-crt/CRT.cs
- aws-crt/IO/ClientBootstrap.cs
- aws-crt/IO/HostResolver.cs
- aws-crt/IO/Logger.cs
- aws-crt/IO/TlsContext.cs
- native/src/http.c
- native/src/http_client.c
- native/src/logger.c
- native/src/tls_ctx_options.c
- tests/HttpClientConnectionTest.cs
- tests/tests.csproj
- tools/DebugApp/DebugApp.csproj
- tools/DebugApp/Program.cs
HTTP works, HTTPS needs work, but it might not be the bindings' fault. Will follow-up after this PR goes in.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> HTTP bindings

- aws-common-runtime/CMakeLists.txt
- aws-crt-http/HttpConnection.cs
- native/src/http_client.c
- tools/DebugApp/Program.cs
Also fixes bugs in test program
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Fixes to make TLS work

- aws-crt-http/HttpConnection.cs
- tools/Elasticurl/Elasticurl.cs
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Converted HTTP API to Tasks/Events

- native/src/event_loop_group.c
- native/src/host_resolver.c
- native/src/http_client.c
- native/src/socket_options.c
- native/src/tls_ctx_options.c
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Use calloc for structure allocs

- aws-crt/aws-crt.csproj
- codebuild/cd/osx-x64-build.sh
- codebuild/cd/promote-release.yml
- codebuild/cd/publish-rc.yml
- codebuild/cd/wait-for-nuget.sh
> OSX pre-built binaries/CD pipeline

- aws-common-runtime/CMakeLists.txt
- aws-common-runtime/cmake/BuildS2N.cmake
- native/CMakeLists.txt
> Link Libcrypto statically on s2n platforms

- .builder/dotnet.py
- NOTICE
- aws-crt-http/Http.cs
- aws-crt-http/HttpConnection.cs
- aws-crt/CRT.cs
- aws-crt/IO/ClientBootstrap.cs
- aws-crt/IO/EventLoopGroup.cs
- aws-crt/IO/HostResolver.cs
- aws-crt/IO/Logger.cs
- aws-crt/IO/SocketOptions.cs
- aws-crt/IO/TlsContext.cs
- aws-crt/NativeAPI.cs
- native/src/client_bootstrap.c
- native/src/crt.c
- native/src/crt.h
- native/src/event_loop_group.c
- native/src/exports.h
- native/src/host_resolver.c
- native/src/http.c
- native/src/http_client.c
- native/src/logger.c
- native/src/socket_options.c
- native/src/tls_ctx_options.c
- tests/ClientBootstrapTest.cs
- tests/EventLoopGroupTest.cs
- tests/ExceptionTest.cs
- tests/HostResolverTest.cs
- tests/SocketOptionsTest.cs
- tests/TlsContextTest.cs
*Issue #, if available:*
*Description of changes:*
> Update license to remove Copyright year.

- native/src/host_resolver.c
> Update submodules to latest

- aws-crt/aws-crt.csproj
> Skip x86 build when not in Windows

- .gitmodules
- native/CMakeLists.txt
* Update to latest submodules
* Move linux build from openssl to aws-lc
> Aws-lc build and submodule update

- codebuild/cd/promote-release.yml
- codebuild/cd/publish-rc.yml
- codebuild/cd/test-rc.yml
- codebuild/cd/test-version-exists.sh
- codebuild/cd/wait-for-nuget.sh
* Step 1 of resurrecting CD pipeline
> Add auth to CD actions

- codebuild/cd/linux-x64-build.yml
> Linux build updates part 1

- codebuild/cd/linux-x64-build.yml
- codebuild/cd/win-build.bat
- codebuild/cd/win-x64-build.yml
- codebuild/cd/win-x86-build.yml
> curl not wget

- codebuild/cd/linux-x64-build.yml
- codebuild/cd/osx-x64-build.sh
- codebuild/cd/win-build-x64.bat
- codebuild/cd/win-build-x86.bat
- codebuild/cd/win-x64-build.yml
- codebuild/cd/win-x86-build.yml
* Try submodule init
* remove generator specs from windows builds
* update mac build
> CDIteration Part 3

- codebuild/cd/linux-x64-build.yml
- codebuild/cd/win-build-x64.bat
- codebuild/cd/win-build-x86.bat
> More experimentation

- aws-crt-auth/aws-crt-auth.csproj
- aws-crt-cal/aws-crt-cal.csproj
- aws-crt-checksums/aws-crt-checksums.csproj
- aws-crt-http/aws-crt-http.csproj
- aws-crt/aws-crt.csproj
> Update for net35 builds

- codebuild/cd/publish-rc-pre-build.bat
* Osx Jenkins artifact path is "special"
> Freakin Jenkins

- codebuild/cd/promote-release.yml
> Last stage has no artifacts

- codebuild/cd/promote-release-build.bat
- codebuild/cd/publish-rc-build.bat
> Use windows path delimeter

- codebuild/cd/linux-x64-build.yml
> Cd to ubuntu18

- codebuild/cd/test-rc.yml
- tests/tests.csproj
> RC Stage - Install and run tests on 2.1, 3.1

- codebuild/cd/linux-arm64-build.sh
> Try to use local workspace directory for download and install

- codebuild/cd/test-rc.yml
> Install dotnet 5.0 on test rc CD step

- codebuild/cd/publish-rc-pre-build.bat
> Use windows environment variable resolution in .bat files

- codebuild/cd/linux-arm64-build.sh
- codebuild/cd/linux-x64-build.yml
- codebuild/cd/osx-arm64-build.sh
- codebuild/cd/osx-x64-build.sh
*Issue #, if available:*
*Description of changes:*
> Update to use 6.0.* .NET for security patch

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/workflows/ci.yml
- .github/workflows/closed-issue-message.yml
- .github/workflows/stale_issue.yml
*Issue #, if available:*
*Description of changes:*
> Issue templates
